### ISSUE TITLE
New UI Overhaul!!

### ISSUE THREAD

**Issue by akkaneror** [makeabilitylab/SoundWatch#10]
Recently, I got some idea for a design overhaul of the App. 
Basically the idea is: we will have three bottom navigation Tabs (Tutorial, Sound Lists, and About). I will send the mocks up later.

1. **Tutorial** will explain user how to use the app and such (assuming they download it from the Play Store with no prior knowledges about our app, so they need to know how to download the WearOS counter part and how those functionalities work).

2. **Sound** Lists is our current default screen, it will have a Three-Dots menu options for user to completely disable and not display some specific sounds (as Hung suggested in his TODO 5). And sounds will be grouped into categories (I will need some suggestion to come up with how many category that we need, what should they be called, and what sounds are included)

3. **About** is the new section that I come up with. It will have our Information of the Makeability lab and links to our GitHub and Website, as well as explain who we are and why do we make such app. I think it's important considering if the many people in the deaf community use our apps, it's better to have some knowledge of who we are, so they know what we do and build trust on us. They might look forward to what we offer in the future, like building a brand name for Makeability lab)

**Comment by akkaneror** [comment]
Sorry for the delays, I had some trouble with windows update recently. 

![Screenshot_20200822-153600.png](https://user-images.githubusercontent.com/42983232/90966944-64bf4600-e48d-11ea-852d-b94a3f632d10.png)

Here is the mock-up UI for what is coming to the App, including additional to Bottom Navigation and categories.
What do you guys think ?

**Comment by rachelgk** [comment]
I like that you added in the description line and the navigation at the bottom.  I think HOME should come before TUTORIAL.  That seems more standard. Also, I know these are just mockups, but when do you think you could put it into the actual categories I organized?  I think that would help me envision it all together looking as realistic as possible.  Thanks!

**Comment by hungngo97** [comment]
Looks great. Though I don't think the tutorial needs to instruct users to install the watch app since it should [auto suggest](https://developer.android.com/training/wearables/apps/packaging) already:
- "On devices running Wear 2.0, when a user installs a phone app that has an associated watch app (either an embedded APK or an APK uploaded via the Play Console), the user gets a watch notification about the available watch app. Tapping the notification opens the watch Play Store, giving the user the option to install the watch app."

But I think it still extremely useful to have tutorial on showing users on how to enable/disable sounds and how to connect to the watch properly as well as troubleshooting when something went wrong

**Comment by higherdefender** [comment]
+1 to all suggestions above. Also, not sure but is the virtical space between "Car Honk" and "Vehicle" more than others? Can't we just the same list type everywhere (more professional) instead of manual setting of spaces?

**Comment by akkaneror** [comment]
> +1 to all suggestions above. Also, not sure but is the virtical space between "Car Honk" and "Vehicle" more than others? Can't we just the same list type everywhere (more professional) instead of manual setting of spaces?

We do have the same margin everywhere, since I set every checkbox to have a pre-defined "margin_tiny" between each Checkbox, plus all other component are scalable Size Unit (scalable DP and SP) (meaning it will scale automatically with different UI sizes), but the Vehicle has a different margin due to a small typo. Thanks for the catch!

**Comment by akkaneror** [comment]
> I like that you added in the description line and the navigation at the bottom. I think HOME should come before TUTORIAL. That seems more standard. Also, I know these are just mockups, but when do you think you could put it into the actual categories I organized? I think that would help me envision it all together looking as realistic as possible. Thanks!

As usual, I sent it as 2 apk files on Drive. The same link that I pinned on our conversation. Let me know if you have any question regarding installing and testing.
