### ISSUE TITLE
Make an FAQ and add recommended/compatible watches

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/SoundWatch#25]
We might consider making an FAQ and adding a list of recommended/compatible watches. The soundwatch@cs team just received this email:

> First of all, amazing idea. I love this so much that I've decided I'm getting my mom a smart watch for Christmas to use with this app. I've been trying to find what watched are compatible but am having trouble finding the information.

We may also consider making a SoundWatch website but I think this is a big decision and depends on how invested we all are in pushing SoundWatch forward in the future. For now, we could just add things to our README.md.

**Comment by akkaneror** [comment]
This issue has been fulfilled until further discussion regarding a SoundWatch website. Our latest version of the app and the README both have an FAQ and a list of recommended/compatible watches. I apologize for not closing this.
