### ISSUE TITLE
UX Improvements

### ISSUE THREAD

**Issue by akkaneror** [makeabilitylab/SoundWatch#3]
### 1. The first improvement is changing the way "recording" button behave on Wearable app. 
I changed the label to "LISTENING" as we press the "mic" icon, to indicate the user that we are recording their surrounding.
I also add a subtle Pulsing animation to further emphasize on that fact alone, because it's important for the users to be aware that they are being listened.

**Comment by higherdefender** [comment]
@rachelgk This is the main UI thread. Would you mind uploading your notes on the UI (the image you sent) so we can keep track?

**Comment by rachelgk** [comment]
![RachelNoteswatchUI](https://user-images.githubusercontent.com/69537908/89963361-4db26580-dbfc-11ea-8b32-7e65bda0e991.png)

**Comment by rachelgk** [comment]
Those are my initial notes on the UI

**Comment by rachelgk** [comment]
![RachelNoteswatchUI](https://user-images.githubusercontent.com/69537908/89963451-805c5e00-dbfc-11ea-80d3-4461909afee3.png)

**Comment by higherdefender** [comment]
Thanks!

**Comment by rachelgk** [comment]
Sorry about that, I accidentally hit close

**Comment by rachelgk** [comment]
<img width="698" alt="Screen Shot 2020-08-11 at 6 28 18 PM" src="https://user-images.githubusercontent.com/69537908/89965004-7fc5c680-dc00-11ea-8e73-9f6f6813927f.png">

**Comment by rachelgk** [comment]
Here are my new notes based on talking with Khoa today and trying it on the actual watch

**Comment by akkaneror** [comment]
Hi Rachel, great talks to you, and that was some constructive feedback!!
I think I can response to some of the points you made so we will have more things to check as completed :)
5. I talked to Hung about this, and from my knowledges as well, but I think it's because of the limitation from the watch itself. In order to have directional sounds, we need multiple speaker placed at multiple direction. The watch only have one speaker, so I don't think we can do anything about it. Correct me if I'm wrong @higherdefender :)
6. The notification on WearOS, from my understanding, only allow text or icon to appear (maybe we can do icon). I wish there is an option for that though.
7,8. Fixed.
9. Those are Google-made Handwashing apps. One of the limitation of a curve screen is that we won't be able to fit word into a beautiful rectangle like on a Phone. So I think it's one of the hardware limitation that even Google themselves can't fix :)

**Comment by higherdefender** [comment]
@rachelgk @akkaneror Some key UX considerations we should also be investigating:

1. Whether the battery consumed by the app is too much or not? 
2. Whether the notifications are overwhelming after wearing the watch for a period of time or not? 
3. Are you getting too attuned to the vibration and forgetting about critical sounds?
4. Are sounds being recognized well? Are important sounds covered? 
5. What is the performance based on context? Have you tried using it in different scenarios such as outdoors, in home, in transit?
6. Did the app interfere with other apps on the watch or not?

These issues will become more clear if you use the watch continuously for 2-3 days (ideally, a week).

**Comment by akkaneror** [comment]
(Responded from Slack)
I can elaborate on some key points while I was wearing it since last weeks.

1. I usually charge my watch at night everyday, but for a whole day usage, I find it sometimes doesn't make it through the very end of the day (my normal usage was 6-7 hours/ day).
But that sometimes is the nature of Wear OS (the latest WearOS chipset was released almost two years ago (the 3100), so the battery and performance is shortcoming, and Google doesn't seem to pay a lot attentions on updating Wear OS than their opponents Apple watchOS)
The current WearOS is based on Android 9, which is almost two years old) and companies hasn't released any major hardware changes. 
But I've heard news on the new chipset 4100 that improve battery life and Google will release some big updates on WearOS at the same time they release Android 11. **(Actually they just announced it today)**

However, the thing that bother me was the Android app will stop running in the foreground after a couple of hours. This is an expected behavior of Android as I learned, unless we specifically tell it not to stop our foreground process in the setting, like I can definitely turn the option called "Not Optimized for battery saving" specifically for the SoundWatch app in Setting, but that is more of a hack and I don't think a typical user will know how to do. Unless we specifically explain that we need the app to run in the foreground constantly to process the audio. 
Some of my early thought would be: a Tutorial on how to do turn on that option in Setting, explain the user what it did and why we should enable that, and then we can let the users choose to enable it or not on their consent?
2. Not really, it doesn't bother me that much. I check my watch constantly and find it more interesting than annoying, but that's just me.
4. None other apps on my watch vibrate, but I understand what you mean by "attuned", one of the ideas I have is that we could make those "Critical sound" like fire alarm and Car Honk to vibrate stronger (or vibrate twice or triple).
5. Speech, Knocking seems accurate (but knocking seems to happen whenever someone taps anything, but that's just the nature of the sound)
Laughing are often somehow misinterpret as Phone Ring?
Water Running and Microwave are accurate from my experience
We don't have a dishwasher so..
I personally try Fire Alarm, it's accurate.
Door-In-Use seems to sometimes mispresent as knocking.
6. 70% of my usage was at home, but when I do groceries, and playing soccer, it recognize others speech and Phone Ring as well.
7. Based on my experience alone, I find the app least obtrusive since we only have a subtle notification.
I did note my user experience down, but it seems I was a bit focusing on the UI a bit too much, so I forgot to let you know my thought on the UX, but that's my collective thought on using it everyday.

**Comment by rachelgk** [comment]
Great questions, I will wear it for a week and then it seems appropriate to construct a user journey map addressing those questions.  I will have to construct the map not  next week but the following week as I'll be out of town next week.  (but I'll still have my laptop for meetings and to stay in touch for anything that arises.)

**Comment by higherdefender** [comment]
Thanks Khoa! These insights are extremely helpful, and will guide us for
improvement!

**Comment by hungngo97** [comment]
Great discussion! I just want to touch up a bit on the proposal for different vibration patterns. As far as I know, Android only allow each Android app to have *exactly* one notification vibration pattern so we cannot have multiple vibration patterns. Though a hack that me @higherdefender discussed before is that we can manually create a vibration when each sound is recognized, though that is more like a hack and I am not sure it will always work, especially when the watch is asleep.

**Comment by hungngo97** [comment]
> However, the thing that bother me was the Android app will stop running in the foreground after a couple of hours\

How much was a couple of hours @akkaneror ? I am just curious because I never run the app until it dies

> a Tutorial on how to do turn on that option in Setting, explain the user what it did and why we should enable that, and then we can let the users choose to enable it or not on their consent?

I agree with this tutorial approach. I tried to look around before too but seems like eventually Android does **NOT** allow any app to run forever so it's good to get user's consent anyway.

**Comment by higherdefender** [comment]
There is a setting in the app to ask permission for running always in
foreground. But yes, I also faced the same problem during user studies
sometimes—the activity closed and hard to be restarted.

Also, not sure if custom vibration pattern is really an issue since android
official docs provide this setting—
https://developer.android.com/reference/android/os/Vibrator
-- 
dhruvjain.info | twitter.com/dj_hci

**Comment by rachelgk** [comment]
I timed it yesterday to see how long it took for the app running in the
background to unpair from the phone, and it was from about 3:50p to 5:30
when it stopped working.  To restart it I had to reopen the app on the
phone and that seemed to re-pair it to the watch.

**Comment by hungngo97** [comment]
> Also, not sure if custom vibration pattern is really an issue since android
official docs provide this setting

Yea this is exactly what I meant as "hack" since it is not a native notification vibration

**Comment by hungngo97** [comment]
> I timed it yesterday to see how long it took for the app running in the
background to unpair from the phone, and it was from about 3:50p to 5:30
when it stopped working.  To restart it I had to reopen the app on the
phone and that seemed to re-pair it to the watch.

Is the phone app running in the foreground?

**Comment by rachelgk** [comment]
Yes I believe I had it open

**Comment by akkaneror** [comment]
> > Also, not sure if custom vibration pattern is really an issue since android
> > official docs provide this setting
> 
> Yea this is exactly what I meant as "hack" since it is not a native notification vibration
https://developer.android.com/reference/kotlin/android/os/Vibrator
Interesting!! I will look into it to see what I can do. 
If it work, I think we can all agree that "High priority" sounds will have 2-3 vibration instead of one. If not, let me know what everyone thinks on this matter.

And I will start to focus on the Phone Application as well, starting from the UI and they way the signal is sent between Phone and Watch and how the UI update correspond to that. since I saw some bugs earlier, when the users chose to Snooze a "sound," a signal is sent to the Phone App, but the UI never got updated while we're in the app (it only update the UI if we don't have the app open (the foreground process is still on)). So that is one thing I'm working on.

**Comment by akkaneror** [comment]
> > > Also, not sure if custom vibration pattern is really an issue since android
> > > official docs provide this setting
> > 
> > 
> > Yea this is exactly what I meant as "hack" since it is not a native notification vibration
> > https://developer.android.com/reference/kotlin/android/os/Vibrator
> > Interesting!! I will look into it to see what I can do.
> > If it work, I think we can all agree that "High priority" sounds will have 2-3 vibration instead of one. If not, let me know what everyone thinks on this matter.
> 
> And I will start to focus on the Phone Application as well, starting from the UI and they way the signal is sent between Phone and Watch and how the UI update correspond to that. since I saw some bugs earlier, when the users chose to Snooze a "sound," a signal is sent to the Phone App, but the UI never got updated while we're in the app (it only update the UI if we don't have the app open (the foreground process is still on)). So that is one thing I'm working on.

**Comment by higherdefender** [comment]
I would hold off on having multiple vibrations for "high priority" sounds
until you can tell which ones are high priority based on reading the DHH
literature. Also, there are other ways of prioritising--for example,
people can just snooze the low priority sounds and in that case, high
priority could be annoying.

Other things sound good.

**Comment by rachelgk** [comment]
Here are the sounds divided into categories and alphabetized.  What do you think about adding ambulance siren to the list and some more outdoor sounds in the future?
Also, some of the sounds are the machine, a noun, and some are written out with "ing" as a verb.  We should pick one or the other to keep it consistent

Categories:

Emergency:
Car Honk
Fire Smoke Alarm

Home:
Alarm Clock
Blender
Chopping
Dishwasher  
Doorbell
Door In Use
Hair Dryer
Knocking
Microwave
Phone Ringing
Water Running
Shaver
Utensils and Cutlery
Toilet Flush
Toothbrush
Vacuum

Human/Animal:
Baby Crying
Dog Barking
Cat Meowing
Snoring
Speech
Laughter

Outdoor:
Vehicle

Tools:
Sawing
Drilling
Hammering

**Comment by higherdefender** [comment]
Looks great!

Seems like 2 sounds are missing from this list—we have a total of 30,
including siren.
-- 
dhruvjain.info | twitter.com/dj_hci

**Comment by akkaneror** [comment]
I think the list is missing Coughing and Typing, but I'm not sure we had Siren or not as I checked labels.txt and didn't see that label.

**Comment by higherdefender** [comment]
Oh yeah, you're right we don't have Siren because it overlapped a lot with
the Hazard alarm.

I read the literature again and think that these are the only sounds we
should keep. The remaining are not important for DHH users
Hazard alarm, Alarm clock, Knocking, Doorbell, Door open/close, Microwave,
Phone ringing, Speech, Dog bark, Cat meow, Baby crying, Vehicle running,
Car horn, Water running, Hammering, Drilling.

For the first release of the SoundWatch app, we should do a very limited
set for accuracy concerns. I suggest testing with these 11:
*Hazard alarm, Knock, Door open/close, Microwave, Speech, Dog bark, Cat
meow, Baby cry, Water pour, Vehicle, Car horn.*
and then further removing 1-3 more sounds that are not recognized well.

**Comment by akkaneror** [comment]
> Oh yeah, you're right we don't have Siren because it overlapped a lot with the Hazard alarm. I read the literature again and think that these are the only sounds we should keep. The remaining are not important for DHH users Hazard alarm, Alarm clock, Knocking, Doorbell, Door open/close, Microwave, Phone ringing, Speech, Dog bark, Cat meow, Baby crying, Vehicle running, Car horn, Water running, Hammering, Drilling. For the first release of the SoundWatch app, we should do a very limited set for accuracy concerns. I suggest testing with these 11: *Hazard alarm, Knock, Door open/close, Microwave, Speech, Dog bark, Cat meow, Baby cry, Water pour, Vehicle, Car horn.* and then further removing 1-3 more sounds that are not recognized well.

I love the shrinked list! I suggest for our first release, we will stick to those 11 sounds and collect some user feedback. With our future updates, we could include an option (in a form of a button or a top-left menu icon) to enable all 30 sounds if user wanted (with some warning about the inaccuracy due to the nature of those sounds).

**Comment by rachelgk** [comment]
![soundwatchjourney](https://user-images.githubusercontent.com/69537908/91236036-c846af00-e6eb-11ea-99e6-8eb34714a3b0.png)

**Comment by rachelgk** [comment]
Here is my journey map. I answered the UX questions posed previously by DJ.  (color coded.)  As you can seen there were some positives and some that gave me pause or were frustrating.  I also tested all the sounds and listed the results.  Feel free to let me know if you have any questions.

**Comment by akkaneror** [comment]
As I think more about a list of sounds that DJ suggest so we can all have discussion about it, a list wouldn't be sufficient for this task. So I make a Trello Board to collect everyone's opinion and edit it as their own please, which I think it's a more scientific way to do this.

For my initial thoughts on the sounds that we can discuss, I categorize the sounds based on 

1. DJ's 11 sounds suggestions
2. Rachel's journey on those false positive and true negative sounds,
3. The feature of each sound (which I think it's a crucial reason for its accuracy)
Because at the end, we want to reduce the number of false positive and true negative as much as possible.
Feel free to comment on the board and discuss furthermore. 

 
https://trello.com/invite/b/j810VkB3/a9d31c7fc53e0dd47f76d6127b88783e/sound-category

**Comment by rachelgk** [comment]
Test of 11 sounds (shortlist)  
8/26/20

WORKS:
Knocking
Microwave
Speech
Vehicle
Dog Bark    No notification sent but was in list of notifications.  
Baby Cry    Also sent a speech notification 
Water Pour  No notification sent but was in list of notifications

DOESN’T WORK:
Hazard Alarm- thought was running water
Door Open/Close- thought was knocking
Cat Meow- no response, then in list of notifications was speech.
Car Horn- thought was fire/smoke alarm

Also came up with fire alarm with no sound happening

**Comment by rachelgk** [comment]
<img width="947" alt="Screen Shot 2020-09-02 at 4 24 27 PM" src="https://user-images.githubusercontent.com/69537908/92048476-a1682880-ed3c-11ea-83e3-a0b32b6ab545.png">

**Comment by rachelgk** [comment]
<img width="775" alt="Screen Shot 2020-09-02 at 4 49 40 PM" src="https://user-images.githubusercontent.com/69537908/92048502-b1800800-ed3c-11ea-915a-977c345f119d.png">
Option 2 for longer names

**Comment by akkaneror** [comment]
Until further UI suggestion from our first released, this issue will be closed.
