### ISSUE TITLE
Decibel seems to be inaccurate for more than half of the time

### ISSUE THREAD

**Issue by akkaneror** [makeabilitylab/SoundWatch#4]
My normal speech is recognize as 127 db, which is way above the "harmful" noise level (85db).
I tried capture my voice with the "Noise" app on watchOS, and it seems to be around 65 db.

**Comment by higherdefender** [comment]
Yeah, this was an error we didn't fix... @akkaneror Could you check our db calculation function and fix? Should be pretty easy. Or could write a new one? This is a nice catch.

**Comment by akkaneror** [comment]
![image](https://user-images.githubusercontent.com/42983232/89746572-54f83880-da6f-11ea-936d-61faac7195f1.png)
This is the current function to display the decibel level, is this what you mean?

**Comment by higherdefender** [comment]
Yeah, and also “audioLabel.db” is calculated somewhere in a function.
Replace that function and here with the correct formula? Do you know how to
calculate loudness? Many resources on the lab
-- 
dhruvjain.info | twitter.com/dj_hci

**Comment by higherdefender** [comment]
@akkaneror were you able to fix this?

**Comment by akkaneror** [comment]
Yes, I understand where the formula to calculate db (the 16 bits audio one), when I check the src code, it seems like we use the correct formula to convert 16 bits audio to db. 
But I'm not quite sure about the calculation above, where we take 90 - db. Assuming the 16 bits one is correct, I think the problem is from the 90 - db formula.
